### ISSUE TITLE
Survey emails - preserving paragraph structure and line spaces between paragraphs

### ISSUE THREAD

**Issue by jshermancody** [developmentseed/api.work.vote#61]
In the emails that we generate to send to local election officials, we type in the email text and create paragraph and indentation and line spacing between paragraphs but all of that disappears in the actual email, which just has a big lump of text. Is there a way to preserve it as type w/ distinct paragraphs, line breaks, etc.? Thanks very much.

**Comment by alyssadelaine** [comment]
@jshermancody If you use HTML in your message, then the styling will be preserved. In the long run, we should change the backend so that you won't need to do that.

For now, you can use `<br>` as a way to insert line breaks, and the paragraph tag(`<p>, </p>`) to insert a paragraph.
`<p>` Here's an example using paragraph tags. `</p>`

If you want to check the styling before you send it, you can use an html editor like [this one](https://htmledit.squarefree.com/). If you like, you can copy and paste this comment into that editor, and you'll see the tags disappear and the format change correspondingly.
